# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('direccion', models.CharField(max_length=200)),
                ('visitas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tapas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('votos', models.IntegerField(default=0)),
                ('barname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Bares')),
            ],
        ),
    ]
